
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Dec 06 2024 11:48:03 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Aboutpagev2 extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.TextElement;
    public bannerimage!: Elements.AssetsElement;
    public aimimage!: Elements.AssetsElement;
    public aboutsummary!: Elements.RichTextElement;
    public missiontitle!: Elements.TextElement;
    public missiontext!: Elements.TextElement;
    public visiontitle!: Elements.TextElement;
    public visiontext!: Elements.TextElement;
    public tailendheading!: Elements.TextElement;
    public tailendsubheading!: Elements.TextElement;
    public tailendimage!: Elements.AssetsElement;
}
