
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Nov 20 2024 12:18:49 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Aboutportfoliopage extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public bannerimage!: Elements.AssetsElement;
    public heading!: Elements.TextElement;
    public image1!: Elements.AssetsElement;
    public content!: Elements.RichTextElement;
    public content2!: Elements.RichTextElement;
    public ctabanner!: Elements.LinkedItemsElement<ContentItem>;
    public pagetitle!: Elements.TextElement;
    public metaTitle!: Elements.TextElement;
    public metadescription!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'meta_title') {
                    return 'metaTitle';
                }
                return elementName;
            })
        });
    }
}
