
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Nov 22 2024 12:25:52 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Aichome extends ContentItem {
    public bannerimage!: Elements.AssetsElement;
    public bannervideolink!: Elements.TextElement;
    public aiclogo!: Elements.AssetsElement;
    public joinheading!: Elements.TextElement;
    public joincontent!: Elements.RichTextElement;
    public ctabutton!: Elements.LinkedItemsElement<ContentItem>;
    public joinvideolink!: Elements.TextElement;
    public joinbackgroundimage!: Elements.AssetsElement;
    public aicheading!: Elements.TextElement;
    public aicdescription!: Elements.RichTextElement;
    public aicimage!: Elements.AssetsElement;
    public aicitems!: Elements.LinkedItemsElement<ContentItem>;
    public datevenuesummary!: Elements.RichTextElement;
    public steps!: Elements.LinkedItemsElement<ContentItem>;
    public benefitsheading!: Elements.TextElement;
    public benefitsdescription!: Elements.RichTextElement;
    public forinvestors!: Elements.AssetsElement;
    public forbusiness!: Elements.AssetsElement;
    public fordevelopers!: Elements.AssetsElement;
    public benefitsforinvestors!: Elements.TextElement;
    public benefitsforbusiness!: Elements.TextElement;
    public benefitsfordevelopers!: Elements.TextElement;
    public benefitsbackground!: Elements.AssetsElement;
    public whocancompeteheading!: Elements.TextElement;
    public whocancompetedescription!: Elements.TextElement;
    public whocancompeteitems!: Elements.LinkedItemsElement<ContentItem>;
    public whocanparticipateheading!: Elements.TextElement;
    public whocanparticipatedescription!: Elements.TextElement;
    public whocanparticipateitems!: Elements.LinkedItemsElement<ContentItem>;
    public competebackground!: Elements.AssetsElement;
    public competeendline1!: Elements.TextElement;
    public competeendline2!: Elements.TextElement;
    public communityheading!: Elements.TextElement;
    public communitydescription!: Elements.TextElement;
    public communitybenefitsheading!: Elements.TextElement;
    public communitybenefits!: Elements.LinkedItemsElement<ContentItem>;
    public seometadata!: Elements.LinkedItemsElement<ContentItem>;
    public primarycolor!: Elements.TextElement;
    public secondarycolor!: Elements.TextElement;
    public digitaleconomylogo!: Elements.AssetsElement;
}
