
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Tue Mar 04 2025 15:50:12 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Aicommunitybenefits extends ContentItem {
    public name!: Elements.TextElement;
    public description!: Elements.TextElement;
}
