
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri May 09 2025 12:30:41 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Aicwinneritem extends ContentItem {
    public name!: Elements.TextElement;
    public designation!: Elements.TextElement;
    public image!: Elements.AssetsElement;
    public categoryname!: Elements.TextElement;
}
