
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Jun 16 2025 00:41:30 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Aim2026page extends ContentItem {
    public aim2026heading!: Elements.TextElement;
    public aim2026description!: Elements.RichTextElement;
    public downloadbrochurelink!: Elements.TextElement;
    public aim2026image!: Elements.AssetsElement;
    public themeline1!: Elements.TextElement;
    public themeline2!: Elements.TextElement;
    public aimdescription!: Elements.RichTextElement;
    public agfimage!: Elements.AssetsElement;
    public agfheading!: Elements.TextElement;
    public agfdescription!: Elements.RichTextElement;
    public venueheading!: Elements.TextElement;
    public venuedescription!: Elements.RichTextElement;
    public venueimage!: Elements.AssetsElement;
    public metadataPagetitle!: Elements.TextElement;
    public metadataMetatitle!: Elements.TextElement;
    public metadataMetadescription!: Elements.TextElement;
    public metadataKeywords!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'metadata__pagetitle') {
                    return 'metadataPagetitle';
                }
                if (elementName === 'metadata__metatitle') {
                    return 'metadataMetatitle';
                }
                if (elementName === 'metadata__metadescription') {
                    return 'metadataMetadescription';
                }
                if (elementName === 'metadata__keywords') {
                    return 'metadataKeywords';
                }
                return elementName;
            })
        });
    }
}
