
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Jun 10 2024 14:29:15 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Aimstartupinvestorpage extends ContentItem {
    public pageTitle!: Elements.TextElement;
    public metaTitle!: Elements.TextElement;
    public metaDescription!: Elements.TextElement;
    public bannerHeading!: Elements.TextElement;
    public bannerImage!: Elements.AssetsElement;
    public bannerBtnName!: Elements.TextElement;
    public bannerBtnLink!: Elements.TextElement;
    public rotateText!: Elements.TextElement;
    public item!: Elements.LinkedItemsElement<ContentItem>;
    public galleryHeading!: Elements.TextElement;
    public galleryItem!: Elements.LinkedItemsElement<ContentItem>;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'page_title') {
                    return 'pageTitle';
                }
                if (elementName === 'meta_title') {
                    return 'metaTitle';
                }
                if (elementName === 'meta_description') {
                    return 'metaDescription';
                }
                if (elementName === 'banner_heading') {
                    return 'bannerHeading';
                }
                if (elementName === 'banner_image') {
                    return 'bannerImage';
                }
                if (elementName === 'banner_btn_name') {
                    return 'bannerBtnName';
                }
                if (elementName === 'banner_btn_link') {
                    return 'bannerBtnLink';
                }
                if (elementName === 'rotate_text') {
                    return 'rotateText';
                }
                if (elementName === 'gallery_heading') {
                    return 'galleryHeading';
                }
                if (elementName === 'gallery_item') {
                    return 'galleryItem';
                }
                return elementName;
            })
        });
    }
}
