
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Oct 31 2022 16:53:58 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Aimstratuppromocode extends ContentItem {
    public promoCode!: Elements.TextElement;
    public discountPercentage!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'promo_code') {
                    return 'promoCode';
                }
                if (elementName === 'discount_percentage') {
                    return 'discountPercentage';
                }
                return elementName;
            })
        });
    }
}
