
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Tue Feb 04 2025 14:25:01 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Awardpage extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.TextElement;
    public bannervideolink!: Elements.TextElement;
    public bannerimage!: Elements.AssetsElement;
    public categoryheading!: Elements.TextElement;
    public categorycontent!: Elements.RichTextElement;
    public categoryitems!: Elements.LinkedItemsElement<ContentItem>;
    public criteriaheading!: Elements.TextElement;
    public criteriacontent!: Elements.RichTextElement;
    public awardwinnerheading!: Elements.TextElement;
    public awardwinnerimages!: Elements.AssetsElement;
    public seometadata!: Elements.LinkedItemsElement<ContentItem>;
}
