
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Feb 21 2025 15:38:55 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Awardjury extends ContentItem {
    public name!: Elements.TextElement;
    public designation!: Elements.TextElement;
    public company!: Elements.TextElement;
    public image!: Elements.AssetsElement;
}
