
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Jul 11 2025 08:22:08 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Awarditem2026 extends ContentItem {
    public name!: Elements.TextElement;
    public description!: Elements.TextElement;
    public companyname!: Elements.TextElement;
    public country!: Elements.TextElement;
    public image!: Elements.AssetsElement;
    public category!: Elements.MultipleChoiceElement;
}
