
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Dec 19 2024 09:50:14 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Awardcriteria extends ContentItem {
    public label!: Elements.TextElement;
    public value!: Elements.TextElement;
    public icon!: Elements.AssetsElement;
}
