
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Tue Dec 10 2024 09:01:17 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Basiccontentpage extends ContentItem {
    public pageTitle!: Elements.TextElement;
    public banner!: Elements.AssetsElement;
    public bannervideolink!: Elements.TextElement;
    public heading!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public metaTitle!: Elements.TextElement;
    public image!: Elements.AssetsElement;
    public ctabutton!: Elements.LinkedItemsElement<ContentItem>;
    public metaDescription!: Elements.TextElement;
    public seometadata!: Elements.LinkedItemsElement<ContentItem>;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'page_title') {
                    return 'pageTitle';
                }
                if (elementName === 'meta_title') {
                    return 'metaTitle';
                }
                if (elementName === 'meta_description') {
                    return 'metaDescription';
                }
                return elementName;
            })
        });
    }
}
