
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Oct 10 2022 16:01:57 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Blogs extends ContentItem {
    public articlesItems!: Elements.LinkedItemsElement<ContentItem>;
    public metaDescription!: Elements.TextElement;
    public popularArticles!: Elements.TextElement;
    public pageTitle!: Elements.TextElement;
    public banner!: Elements.AssetsElement;
    public metaTitle!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'articles_items') {
                    return 'articlesItems';
                }
                if (elementName === 'meta_description') {
                    return 'metaDescription';
                }
                if (elementName === 'popular_articles') {
                    return 'popularArticles';
                }
                if (elementName === 'page_title') {
                    return 'pageTitle';
                }
                if (elementName === 'meta_title') {
                    return 'metaTitle';
                }
                return elementName;
            })
        });
    }
}
