
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Oct 10 2022 16:01:57 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Bochurepage extends ContentItem {
    public metaTitle!: Elements.TextElement;
    public phoneLocale!: Elements.TextElement;
    public heading!: Elements.TextElement;
    public emailLocale!: Elements.TextElement;
    public natureOfBusinessLocale!: Elements.TextElement;
    public countryLocale!: Elements.TextElement;
    public firstNameLocale!: Elements.TextElement;
    public pageTitle!: Elements.TextElement;
    public messageLocale!: Elements.TextElement;
    public pillarInterestedLocale!: Elements.TextElement;
    public banner!: Elements.AssetsElement;
    public organizationLocale!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public jobTitleLocale!: Elements.TextElement;
    public submitLocale!: Elements.TextElement;
    public lastNameLocale!: Elements.TextElement;
    public metaDescription!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'meta_title') {
                    return 'metaTitle';
                }
                if (elementName === 'phone_locale') {
                    return 'phoneLocale';
                }
                if (elementName === 'email_locale') {
                    return 'emailLocale';
                }
                if (elementName === 'nature_of_business_locale') {
                    return 'natureOfBusinessLocale';
                }
                if (elementName === 'country_locale') {
                    return 'countryLocale';
                }
                if (elementName === 'first_name_locale') {
                    return 'firstNameLocale';
                }
                if (elementName === 'page_title') {
                    return 'pageTitle';
                }
                if (elementName === 'message_locale') {
                    return 'messageLocale';
                }
                if (elementName === 'pillar_interested_locale') {
                    return 'pillarInterestedLocale';
                }
                if (elementName === 'organization_locale') {
                    return 'organizationLocale';
                }
                if (elementName === 'job_title_locale') {
                    return 'jobTitleLocale';
                }
                if (elementName === 'submit_locale') {
                    return 'submitLocale';
                }
                if (elementName === 'last_name_locale') {
                    return 'lastNameLocale';
                }
                if (elementName === 'meta_description') {
                    return 'metaDescription';
                }
                return elementName;
            })
        });
    }
}
