
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Tue Sep 10 2024 15:53:53 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Buttonitem extends ContentItem {
    public name!: Elements.TextElement;
    public link!: Elements.TextElement;
    public target!: Elements.NumberElement;
}
