
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Jan 24 2025 17:29:58 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Conferenceparticipantspartners2025 extends ContentItem {
    public items!: Elements.LinkedItemsElement<ContentItem>;
}
