
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Oct 04 2024 11:36:47 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Conferencedates extends ContentItem {
    public dateString!: Elements.TextElement;
    public date!: Elements.DateTimeElement;
    public sessions!: Elements.LinkedItemsElement<ContentItem>;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'date_string') {
                    return 'dateString';
                }
                return elementName;
            })
        });
    }
}
