
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Jul 10 2025 10:51:48 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Conferencepage2026 extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public aboutheading!: Elements.TextElement;
    public aboutdescription!: Elements.TextElement;
    public ctabuttonname!: Elements.TextElement;
    public ctabuttonlink!: Elements.TextElement;
    public planerysessionheading!: Elements.TextElement;
    public planerysessionimage!: Elements.AssetsElement;
    public planerysessiondescription!: Elements.TextElement;
    public thematicareaheading!: Elements.TextElement;
    public thematicareaimage!: Elements.AssetsElement;
    public thematicareadescription!: Elements.TextElement;
    public sideforumheading!: Elements.TextElement;
    public sideforumdescription!: Elements.TextElement;
    public sideforumitems!: Elements.LinkedItemsElement<ContentItem>;
    public ctacard!: Elements.LinkedItemsElement<ContentItem>;
    public investmentdestinationitems!: Elements.LinkedItemsElement<ContentItem>;
    public metadataPagetitle!: Elements.TextElement;
    public metadataMetatitle!: Elements.TextElement;
    public metadataMetadescription!: Elements.TextElement;
    public metadataKeywords!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'metadata__pagetitle') {
                    return 'metadataPagetitle';
                }
                if (elementName === 'metadata__metatitle') {
                    return 'metadataMetatitle';
                }
                if (elementName === 'metadata__metadescription') {
                    return 'metadataMetadescription';
                }
                if (elementName === 'metadata__keywords') {
                    return 'metadataKeywords';
                }
                return elementName;
            })
        });
    }
}
