
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Aug 13 2025 15:12:34 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Ctablock extends ContentItem {
    public name!: Elements.TextElement;
    public ctabuttonname!: Elements.TextElement;
    public ctabuttonlink!: Elements.TextElement;
    public isexternal!: Elements.MultipleChoiceElement;
    public backgroundimage!: Elements.AssetsElement;
}
