
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Nov 01 2024 11:12:55 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class EntrepreneurPortfolio extends ContentItem {
    public pagetitle!: Elements.TextElement;
    public metatitle!: Elements.TextElement;
    public metadescription!: Elements.TextElement;
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.TextElement;
    public dateandvenue!: Elements.TextElement;
    public bannercta!: Elements.LinkedItemsElement<ContentItem>;
    public bannerimage!: Elements.AssetsElement;
    public aboutheading!: Elements.TextElement;
    public aboutparagraph!: Elements.RichTextElement;
    public aboutbackgroundimage!: Elements.AssetsElement;
    public featureheading!: Elements.TextElement;
    public featuresubheading!: Elements.TextElement;
    public features!: Elements.LinkedItemsElement<ContentItem>;
    public categoriesheading!: Elements.TextElement;
    public categoriesitems!: Elements.LinkedItemsElement<ContentItem>;
    public focusSectorsHeading!: Elements.TextElement;
    public focusSectorsItems!: Elements.LinkedItemsElement<ContentItem>;
    public benefitsheading!: Elements.TextElement;
    public benefits!: Elements.LinkedItemsElement<ContentItem>;
    public benefitButtons!: Elements.LinkedItemsElement<ContentItem>;
    public whoparticipateheading!: Elements.TextElement;
    public whoparticipateitems!: Elements.LinkedItemsElement<ContentItem>;
    public keyplayersheading!: Elements.TextElement;
    public keyplayersitems!: Elements.LinkedItemsElement<ContentItem>;
    public speakersheading!: Elements.TextElement;
    public speakersitems!: Elements.LinkedItemsElement<ContentItem>;
    public keyagendaitems!: Elements.LinkedItemsElement<ContentItem>;
    public keyagendabackgroundimage!: Elements.AssetsElement;
    public ctacardsheading!: Elements.TextElement;
    public ctacarditems!: Elements.LinkedItemsElement<ContentItem>;
    public tailendctaheading!: Elements.TextElement;
    public tailendctaimage!: Elements.AssetsElement;
    public tailendctabutton!: Elements.LinkedItemsElement<ContentItem>;
    public faq!: Elements.LinkedItemsElement<ContentItem>;
    public brandcolorcode!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'focus_sectors_heading') {
                    return 'focusSectorsHeading';
                }
                if (elementName === 'focus_sectors_items') {
                    return 'focusSectorsItems';
                }
                if (elementName === 'benefit_buttons') {
                    return 'benefitButtons';
                }
                return elementName;
            })
        });
    }
}
