
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Apr 04 2025 16:44:11 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Eventinformationpage extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.TextElement;
    public bannerimage!: Elements.AssetsElement;
    public date!: Elements.TextElement;
    public cta!: Elements.LinkedItemsElement<ContentItem>;
    public aboutheading!: Elements.TextElement;
    public aboutcontent!: Elements.RichTextElement;
    public themeheading!: Elements.TextElement;
    public theme!: Elements.TextElement;
    public directionsheading!: Elements.TextElement;
    public directionitems!: Elements.LinkedItemsElement<ContentItem>;
    public badgecollection!: Elements.TextElement;
    public badgecollectioncontent!: Elements.RichTextElement;
    public countersheading!: Elements.TextElement;
    public counterssubheading!: Elements.TextElement;
    public counterscontent!: Elements.RichTextElement;
    public admissionpolicyheading!: Elements.TextElement;
    public admissionpolicycontent!: Elements.RichTextElement;
    public badgepolicyheading!: Elements.TextElement;
    public badgepolicycontent!: Elements.RichTextElement;
    public policyhelpertext!: Elements.TextElement;
    public downloadappheading!: Elements.TextElement;
    public appstorelink!: Elements.TextElement;
    public playstorelink!: Elements.TextElement;
    public qrcode!: Elements.AssetsElement;
    public metadataPagetitle!: Elements.TextElement;
    public metadataMetatitle!: Elements.TextElement;
    public metadataMetadescription!: Elements.TextElement;
    public metadataKeywords!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'metadata__pagetitle') {
                    return 'metadataPagetitle';
                }
                if (elementName === 'metadata__metatitle') {
                    return 'metadataMetatitle';
                }
                if (elementName === 'metadata__metadescription') {
                    return 'metadataMetadescription';
                }
                if (elementName === 'metadata__keywords') {
                    return 'metadataKeywords';
                }
                return elementName;
            })
        });
    }
}
