
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Dec 06 2024 12:34:00 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Eventhighlights extends ContentItem {
    public bannervideolink!: Elements.TextElement;
    public themebackground!: Elements.AssetsElement;
    public themetitle!: Elements.TextElement;
    public themeheading!: Elements.TextElement;
    public themesubheading!: Elements.TextElement;
    public summary!: Elements.TextElement;
    public venueheading!: Elements.TextElement;
    public venuecontent!: Elements.RichTextElement;
    public venuebackgroundimage!: Elements.AssetsElement;
    public venueaddress!: Elements.TextElement;
    public eventdate!: Elements.TextElement;
    public participatingbenefitsheading!: Elements.TextElement;
    public participatingbenefits!: Elements.LinkedItemsElement<ContentItem>;
    public endheading!: Elements.TextElement;
    public endsubheading!: Elements.TextElement;
}
