
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Nov 04 2024 11:07:40 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Faqitem extends ContentItem {
    public title!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public keywords!: Elements.TextElement;
}
