
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Nov 04 2024 11:07:40 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Fdiawardpage extends ContentItem {
    public pagetitle!: Elements.TextElement;
    public metatitle!: Elements.TextElement;
    public metadescription!: Elements.TextElement;
    public bannerHeading!: Elements.TextElement;
    public bannerContent!: Elements.TextElement;
    public bannerBackgroundUrl!: Elements.TextElement;
    public awardCeremonyHeading!: Elements.TextElement;
    public awardCeremonyContent!: Elements.RichTextElement;
    public awardCeremonyCtaButton!: Elements.LinkedItemsElement<ContentItem>;
    public guidelinesHeading!: Elements.TextElement;
    public guidelinesitems!: Elements.LinkedItemsElement<ContentItem>;
    public awardCategoriesHeading!: Elements.TextElement;
    public awardCategoriesItems!: Elements.LinkedItemsElement<ContentItem>;
    public awardWinnerTitle!: Elements.TextElement;
    public awardWinnerHeading!: Elements.TextElement;
    public awardWinnerImage!: Elements.AssetsElement;
    public awardwinneritems!: Elements.LinkedItemsElement<ContentItem>;
    public bookspotctaHeading!: Elements.TextElement;
    public bookspotcta!: Elements.LinkedItemsElement<ContentItem>;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'banner_heading') {
                    return 'bannerHeading';
                }
                if (elementName === 'banner_content') {
                    return 'bannerContent';
                }
                if (elementName === 'banner_background_url') {
                    return 'bannerBackgroundUrl';
                }
                if (elementName === 'award_ceremony_heading') {
                    return 'awardCeremonyHeading';
                }
                if (elementName === 'award_ceremony_content') {
                    return 'awardCeremonyContent';
                }
                if (elementName === 'award_ceremony_cta_button') {
                    return 'awardCeremonyCtaButton';
                }
                if (elementName === 'guidelines_heading') {
                    return 'guidelinesHeading';
                }
                if (elementName === 'award_categories_heading') {
                    return 'awardCategoriesHeading';
                }
                if (elementName === 'award_categories_items') {
                    return 'awardCategoriesItems';
                }
                if (elementName === 'award_winner_title') {
                    return 'awardWinnerTitle';
                }
                if (elementName === 'award_winner_heading') {
                    return 'awardWinnerHeading';
                }
                if (elementName === 'award_winner_image') {
                    return 'awardWinnerImage';
                }
                if (elementName === 'bookspotcta_heading') {
                    return 'bookspotctaHeading';
                }
                return elementName;
            })
        });
    }
}
