
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Jun 16 2025 16:30:09 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Featureactivitespageitemmodel2026 extends ContentItem {
    public ctacardimage!: Elements.AssetsElement;
    public ctacardlink!: Elements.TextElement;
    public bannerimage!: Elements.AssetsElement;
    public activitiesitems!: Elements.LinkedItemsElement<ContentItem>;
}
