
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Feb 13 2025 08:59:41 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Form extends ContentItem {
    public formsubmit!: Elements.TextElement;
    public fielditems!: Elements.LinkedItemsElement<ContentItem>;
    public seometadataA981ccfPagetitle!: Elements.TextElement;
    public seometadataA981ccfMetatitle!: Elements.TextElement;
    public seometadataA981ccfMetadescription!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'seometadata_a981ccf__pagetitle') {
                    return 'seometadataA981ccfPagetitle';
                }
                if (elementName === 'seometadata_a981ccf__metatitle') {
                    return 'seometadataA981ccfMetatitle';
                }
                if (elementName === 'seometadata_a981ccf__metadescription') {
                    return 'seometadataA981ccfMetadescription';
                }
                return elementName;
            })
        });
    }
}
