
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Feb 13 2025 08:59:41 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Formfielditem extends ContentItem {
    public label!: Elements.TextElement;
    public id!: Elements.TextElement;
    public name!: Elements.TextElement;
    public type!: Elements.TextElement;
    public value!: Elements.TextElement;
    public placeholder!: Elements.TextElement;
    public required!: Elements.MultipleChoiceElement;
}
