
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri May 30 2025 17:30:06 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Global2026 extends ContentItem {
    public aimlogo!: Elements.AssetsElement;
    public ministrylogos!: Elements.LinkedItemsElement<ContentItem>;
    public menuitems!: Elements.LinkedItemsElement<ContentItem>;
    public ctabutton!: Elements.LinkedItemsElement<ContentItem>;
    public sociallinksFacebookurl!: Elements.TextElement;
    public sociallinksInstagramurl!: Elements.TextElement;
    public sociallinksLinkedinurl!: Elements.TextElement;
    public sociallinksXurl!: Elements.TextElement;
    public sociallinksYoutubeurl!: Elements.TextElement;
    public themesettingsPrimarycolor!: Elements.TextElement;
    public themesettingsSecondarycolor!: Elements.TextElement;
    public themesettingsBackgroundcolor!: Elements.TextElement;
    public themesettingsCustomcssvariables!: Elements.RichTextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'sociallinks__facebookurl') {
                    return 'sociallinksFacebookurl';
                }
                if (elementName === 'sociallinks__instagramurl') {
                    return 'sociallinksInstagramurl';
                }
                if (elementName === 'sociallinks__linkedinurl') {
                    return 'sociallinksLinkedinurl';
                }
                if (elementName === 'sociallinks__xurl') {
                    return 'sociallinksXurl';
                }
                if (elementName === 'sociallinks__youtubeurl') {
                    return 'sociallinksYoutubeurl';
                }
                if (elementName === 'themesettings__primarycolor') {
                    return 'themesettingsPrimarycolor';
                }
                if (elementName === 'themesettings__secondarycolor') {
                    return 'themesettingsSecondarycolor';
                }
                if (elementName === 'themesettings__backgroundcolor') {
                    return 'themesettingsBackgroundcolor';
                }
                if (elementName === 'themesettings__customcssvariables') {
                    return 'themesettingsCustomcssvariables';
                }
                return elementName;
            })
        });
    }
}
