
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Dec 27 2024 13:47:26 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Gmawardspage extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public bannercontent!: Elements.TextElement;
    public bannerbackgroundurl!: Elements.TextElement;
    public awardceremonyheading!: Elements.TextElement;
    public awardceremonycontent!: Elements.RichTextElement;
    public awardceremonyctabutton!: Elements.LinkedItemsElement<ContentItem>;
    public guidelinesheading!: Elements.TextElement;
    public guidelinesitems!: Elements.LinkedItemsElement<ContentItem>;
    public whyparticipateheading!: Elements.TextElement;
    public whyparticipateitems!: Elements.LinkedItemsElement<ContentItem>;
    public whocanapplyheading!: Elements.TextElement;
    public whocanapplyitems!: Elements.LinkedItemsElement<ContentItem>;
    public whocanapplybackground!: Elements.AssetsElement;
    public evaluationcriteriaheading!: Elements.TextElement;
    public evaluationcriteriasubheading!: Elements.TextElement;
    public evaluationcriteriaitems!: Elements.LinkedItemsElement<ContentItem>;
    public awardcategoriesheading!: Elements.TextElement;
    public awardcategoriesitems!: Elements.LinkedItemsElement<ContentItem>;
    public awardwinnertitle!: Elements.TextElement;
    public awardwinnerheading!: Elements.TextElement;
    public awardwinnerimage!: Elements.AssetsElement;
    public awardwinneritems!: Elements.LinkedItemsElement<ContentItem>;
    public awardsceremonydate!: Elements.TextElement;
    public finaldate!: Elements.TextElement;
    public venue!: Elements.TextElement;
    public bookspotcta!: Elements.LinkedItemsElement<ContentItem>;
    public caption!: Elements.TextElement;
    public bookspotctabackground!: Elements.AssetsElement;
    public colorcode!: Elements.TextElement;
    public seometadata!: Elements.LinkedItemsElement<ContentItem>;
}
