
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Dec 09 2024 13:24:50 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Homepage extends ContentItem {
    public pagetitle!: Elements.TextElement;
    public metatitle!: Elements.TextElement;
    public metadescription!: Elements.TextElement;
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.TextElement;
    public datevenue!: Elements.TextElement;
    public bannerctabutton!: Elements.LinkedItemsElement<ContentItem>;
    public backgroundvideolink!: Elements.TextElement;
    public statistics!: Elements.LinkedItemsElement<ContentItem>;
    public themeheading!: Elements.TextElement;
    public themesubheading!: Elements.TextElement;
    public themeimage!: Elements.AssetsElement;
    public targetaudientsheading!: Elements.TextElement;
    public targetaudientssubheading!: Elements.TextElement;
    public targetaudientscta!: Elements.LinkedItemsElement<ContentItem>;
    public portfolioctaheading!: Elements.TextElement;
    public portfolioctasubheading!: Elements.TextElement;
    public portfolioctacards!: Elements.LinkedItemsElement<ContentItem>;
    public sustainableheading!: Elements.TextElement;
    public sustainablecontent1!: Elements.RichTextElement;
    public sustainableimage!: Elements.AssetsElement;
    public sustainablecontent2!: Elements.RichTextElement;
    public sustainablebackground!: Elements.AssetsElement;
    public testimonials!: Elements.LinkedItemsElement<ContentItem>;
    public endtailheading!: Elements.TextElement;
    public endtailcontent!: Elements.RichTextElement;
    public endtailbutton!: Elements.LinkedItemsElement<ContentItem>;
    public seometadata!: Elements.LinkedItemsElement<ContentItem>;
}
