
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Jul 17 2025 12:41:49 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Homepage2026 extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.TextElement;
    public datevenue!: Elements.TextElement;
    public bannervideolink!: Elements.TextElement;
    public bannerimage!: Elements.AssetsElement;
    public bannercta!: Elements.LinkedItemsElement<ContentItem>;
    public statsheading!: Elements.TextElement;
    public statscontent!: Elements.RichTextElement;
    public statsitems!: Elements.LinkedItemsElement<ContentItem>;
    public downloadreportlink!: Elements.TextElement;
    public themeline1!: Elements.TextElement;
    public themeline2!: Elements.TextElement;
    public themectatext!: Elements.TextElement;
    public themectabuttontext!: Elements.TextElement;
    public themectalink!: Elements.TextElement;
    public pillarheading!: Elements.TextElement;
    public pillaritems!: Elements.LinkedItemsElement<ContentItem>;
    public pillarctabuttontext!: Elements.TextElement;
    public pillarctalink!: Elements.TextElement;
    public featuresheading!: Elements.TextElement;
    public featuresitems!: Elements.LinkedItemsElement<ContentItem>;
    public targetaudientsheading!: Elements.TextElement;
    public targetaudientsitems!: Elements.LinkedItemsElement<ContentItem>;
    public testimonialsheading!: Elements.TextElement;
    public testimonialitems!: Elements.LinkedItemsElement<ContentItem>;
    public testimonialctaname!: Elements.TextElement;
    public testimonialctalink!: Elements.TextElement;
    public blogsheading!: Elements.TextElement;
    public blogsctaname!: Elements.TextElement;
    public blogsctalink!: Elements.TextElement;
    public youtubeheading!: Elements.TextElement;
    public youtubesubheading!: Elements.TextElement;
    public youtubeitems!: Elements.LinkedItemsElement<ContentItem>;
    public faqheading!: Elements.TextElement;
    public faqitems!: Elements.LinkedItemsElement<ContentItem>;
    public metadataPagetitle!: Elements.TextElement;
    public metadataMetatitle!: Elements.TextElement;
    public metadataMetadescription!: Elements.TextElement;
    public metadataKeywords!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'metadata__pagetitle') {
                    return 'metadataPagetitle';
                }
                if (elementName === 'metadata__metatitle') {
                    return 'metadataMetatitle';
                }
                if (elementName === 'metadata__metadescription') {
                    return 'metadataMetadescription';
                }
                if (elementName === 'metadata__keywords') {
                    return 'metadataKeywords';
                }
                return elementName;
            })
        });
    }
}
