
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Aug 13 2025 15:12:34 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Investmentdestinationitem2026 extends ContentItem {
    public image!: Elements.AssetsElement;
    public heading!: Elements.TextElement;
    public countryname!: Elements.TextElement;
    public aboutdescription!: Elements.TextElement;
    public websitebtnname!: Elements.TextElement;
    public websitebtnlink!: Elements.TextElement;
    public videoheading!: Elements.TextElement;
    public videolink!: Elements.TextElement;
    public videodescription!: Elements.RichTextElement;
    public relatedheading!: Elements.TextElement;
    public relateditems!: Elements.LinkedItemsElement<ContentItem>;
    public metadataPagetitle!: Elements.TextElement;
    public metadataMetatitle!: Elements.TextElement;
    public metadataMetadescription!: Elements.TextElement;
    public metadataKeywords!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'metadata__pagetitle') {
                    return 'metadataPagetitle';
                }
                if (elementName === 'metadata__metatitle') {
                    return 'metadataMetatitle';
                }
                if (elementName === 'metadata__metadescription') {
                    return 'metadataMetadescription';
                }
                if (elementName === 'metadata__keywords') {
                    return 'metadataKeywords';
                }
                return elementName;
            })
        });
    }
}
