
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Jun 26 2025 10:03:01 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Matchmakingitem extends ContentItem {
    public name!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public buttonname!: Elements.TextElement;
    public link!: Elements.TextElement;
    public type!: Elements.MultipleChoiceElement;
    public code!: Elements.MultipleChoiceElement;
}
