
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Tue Jun 03 2025 09:33:38 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Menuitem2026 extends ContentItem {
    public name!: Elements.TextElement;
    public link!: Elements.TextElement;
    public isexternal!: Elements.MultipleChoiceElement;
    public subitems!: Elements.LinkedItemsElement<ContentItem>;
}
