
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Feb 10 2025 11:26:10 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Menuv2 extends ContentItem {
    public aimlogo!: Elements.AssetsElement;
    public ministrylogos!: Elements.LinkedItemsElement<ContentItem>;
    public menuitems!: Elements.LinkedItemsElement<ContentItem>;
}
