
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Jul 11 2025 11:00:46 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Mouentityitem extends ContentItem {
    public name!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public logo!: Elements.AssetsElement;
    public image!: Elements.AssetsElement;
    public websitelink!: Elements.TextElement;
}
