
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Jul 11 2025 11:00:46 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Moupage2026 extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.TextElement;
    public moucount!: Elements.TextElement;
    public moucountheading!: Elements.TextElement;
    public moucountdescription!: Elements.TextElement;
    public ctabuttonname!: Elements.TextElement;
    public ctabuttonlink!: Elements.TextElement;
    public mouitems!: Elements.LinkedItemsElement<ContentItem>;
    public companytocompanyheading!: Elements.TextElement;
    public companytocompanydescription!: Elements.TextElement;
    public companytocompanybuttonname!: Elements.TextElement;
    public companytocompanybuttonlink!: Elements.TextElement;
    public aimtocompanyheading!: Elements.TextElement;
    public aimtocompanydescription!: Elements.TextElement;
    public aimtocompanybuttonname!: Elements.TextElement;
    public aimtocompanybuttonlink!: Elements.TextElement;
    public featuredmouheading!: Elements.TextElement;
    public featuredmouitems!: Elements.LinkedItemsElement<ContentItem>;
    public metadataPagetitle!: Elements.TextElement;
    public metadataMetatitle!: Elements.TextElement;
    public metadataMetadescription!: Elements.TextElement;
    public metadataKeywords!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'metadata__pagetitle') {
                    return 'metadataPagetitle';
                }
                if (elementName === 'metadata__metatitle') {
                    return 'metadataMetatitle';
                }
                if (elementName === 'metadata__metadescription') {
                    return 'metadataMetadescription';
                }
                if (elementName === 'metadata__keywords') {
                    return 'metadataKeywords';
                }
                return elementName;
            })
        });
    }
}
