
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Tue Dec 17 2024 11:33:38 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Nationalprocess extends ContentItem {
    public name!: Elements.TextElement;
    public content!: Elements.TextElement;
    public icon!: Elements.AssetsElement;
}
