
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Feb 10 2025 16:48:21 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Newmenuitem extends ContentItem {
    public name!: Elements.TextElement;
    public link!: Elements.TextElement;
    public subitem!: Elements.LinkedItemsElement<ContentItem>;
    public isagenda!: Elements.MultipleChoiceElement;
}
