
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Sat Jun 14 2025 19:34:08 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Opencallsitem extends ContentItem {
    public name!: Elements.TextElement;
    public image!: Elements.AssetsElement;
    public date!: Elements.TextElement;
    public buttonname!: Elements.TextElement;
    public buttonlink!: Elements.TextElement;
    public status!: Elements.MultipleChoiceElement;
}
