
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Apr 25 2024 12:44:21 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Partnerspage extends ContentItem {
    public homePageTitle!: Elements.TextElement;
    public metaTitle!: Elements.TextElement;
    public partners!: Elements.LinkedItemsElement<ContentItem>;
    public viewAll!: Elements.TextElement;
    public visitWebsite!: Elements.TextElement;
    public banner!: Elements.AssetsElement;
    public pageTitle!: Elements.TextElement;
    public partnerscontainer!: Elements.LinkedItemsElement<ContentItem>;
    public heading!: Elements.TextElement;
    public metaDescription!: Elements.TextElement;
    public content!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'home_page_title') {
                    return 'homePageTitle';
                }
                if (elementName === 'meta_title') {
                    return 'metaTitle';
                }
                if (elementName === 'view_all') {
                    return 'viewAll';
                }
                if (elementName === 'visit_website') {
                    return 'visitWebsite';
                }
                if (elementName === 'page_title') {
                    return 'pageTitle';
                }
                if (elementName === 'meta_description') {
                    return 'metaDescription';
                }
                return elementName;
            })
        });
    }
}
