
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Dec 06 2024 12:34:00 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Participatingbenefits extends ContentItem {
    public name!: Elements.TextElement;
    public benefititems!: Elements.LinkedItemsElement<ContentItem>;
}
