
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Tue Jul 08 2025 08:44:54 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Pillardetailpageitem extends ContentItem {
    public slug!: Elements.UrlSlugElement;
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.TextElement;
    public tracksheading!: Elements.TextElement;
    public trackitems!: Elements.LinkedItemsElement<ContentItem>;
    public sustainableheading!: Elements.TextElement;
    public sustainabledescription!: Elements.TextElement;
    public sustainablectaname!: Elements.TextElement;
    public sustainablectalink!: Elements.TextElement;
    public sustainableitems!: Elements.LinkedItemsElement<ContentItem>;
    public investmentdestinationheading!: Elements.TextElement;
    public investmentdestinationitems!: Elements.LinkedItemsElement<ContentItem>;
    public featuresactivitiesheading!: Elements.TextElement;
    public featuresitems!: Elements.LinkedItemsElement<ContentItem>;
    public metadataPagetitle!: Elements.TextElement;
    public metadataMetatitle!: Elements.TextElement;
    public metadataMetadescription!: Elements.TextElement;
    public metadataKeywords!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'metadata__pagetitle') {
                    return 'metadataPagetitle';
                }
                if (elementName === 'metadata__metatitle') {
                    return 'metadataMetatitle';
                }
                if (elementName === 'metadata__metadescription') {
                    return 'metadataMetadescription';
                }
                if (elementName === 'metadata__keywords') {
                    return 'metadataKeywords';
                }
                return elementName;
            })
        });
    }
}
