
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Oct 17 2024 13:59:09 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Portfoliocard extends ContentItem {
    public name!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public image!: Elements.AssetsElement;
    public link!: Elements.TextElement;
    public brandcolorcode!: Elements.TextElement;
}
