
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Aug 21 2024 10:55:01 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Portfoliofeatures extends ContentItem {
    public heading!: Elements.TextElement;
    public subheading!: Elements.TextElement;
    public items!: Elements.LinkedItemsElement<ContentItem>;
}
