
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Dec 04 2024 12:04:57 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Portfoliopage extends ContentItem {
    public pagetitle!: Elements.TextElement;
    public metatitle!: Elements.TextElement;
    public metadescription!: Elements.TextElement;
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.TextElement;
    public dateandvenue!: Elements.TextElement;
    public bannercta!: Elements.LinkedItemsElement<ContentItem>;
    public bannervideolink!: Elements.TextElement;
    public bannerimage!: Elements.AssetsElement;
    public aboutheading!: Elements.TextElement;
    public aboutparagraph!: Elements.RichTextElement;
    public aboutparagraph2!: Elements.RichTextElement;
    public aboutbackgroundimage!: Elements.AssetsElement;
    public featureheading!: Elements.TextElement;
    public featuresubheading!: Elements.TextElement;
    public features!: Elements.LinkedItemsElement<ContentItem>;
    public featuresbriefheading!: Elements.TextElement;
    public featuresbriefcontent!: Elements.RichTextElement;
    public thematicareaheading!: Elements.TextElement;
    public thematicareaitems!: Elements.LinkedItemsElement<ContentItem>;
    public thematicareabackground!: Elements.AssetsElement;
    public attributesHeading1!: Elements.TextElement;
    public attributesItems1!: Elements.LinkedItemsElement<ContentItem>;
    public whoparticipateheading!: Elements.TextElement;
    public whoparticipateitems!: Elements.LinkedItemsElement<ContentItem>;
    public whyparticipateheading!: Elements.TextElement;
    public whyparticipatesubheading!: Elements.TextElement;
    public whyparticipateitems!: Elements.LinkedItemsElement<ContentItem>;
    public keyplayersheading!: Elements.TextElement;
    public keyplayersitems!: Elements.LinkedItemsElement<ContentItem>;
    public keyexhibitorheading!: Elements.TextElement;
    public keyexhibitoritem!: Elements.LinkedItemsElement<ContentItem>;
    public currentspeakersheading!: Elements.TextElement;
    public currentspeakersitems!: Elements.LinkedItemsElement<ContentItem>;
    public speakersheading!: Elements.TextElement;
    public speakersitems!: Elements.LinkedItemsElement<ContentItem>;
    public currentpartnersheading!: Elements.TextElement;
    public currentparntersitems!: Elements.LinkedItemsElement<ContentItem>;
    public keyagendaheading!: Elements.TextElement;
    public keyagendaitems!: Elements.LinkedItemsElement<ContentItem>;
    public keyagendabackgroundimage!: Elements.AssetsElement;
    public fdiInvestmentDestinationHeading!: Elements.TextElement;
    public fdiInvestmentDestinationCta!: Elements.TextElement;
    public fdiInvestmentDestinationItems!: Elements.LinkedItemsElement<ContentItem>;
    public ctabannerheading!: Elements.TextElement;
    public ctabannersubheading!: Elements.TextElement;
    public ctacardsheading!: Elements.TextElement;
    public ctacarditems!: Elements.LinkedItemsElement<ContentItem>;
    public attributesHeading2!: Elements.TextElement;
    public attributesItems2!: Elements.LinkedItemsElement<ContentItem>;
    public benefitsheading!: Elements.TextElement;
    public benefitssubheading!: Elements.TextElement;
    public benefits!: Elements.LinkedItemsElement<ContentItem>;
    public benefitsbackground!: Elements.AssetsElement;
    public benefitsButtons!: Elements.LinkedItemsElement<ContentItem>;
    public tailendctaheading!: Elements.TextElement;
    public tailendctaimage!: Elements.AssetsElement;
    public tailendctabutton!: Elements.LinkedItemsElement<ContentItem>;
    public chambersTalkHeading!: Elements.TextElement;
    public chambersTalkImage!: Elements.AssetsElement;
    public chambersTalkContent!: Elements.RichTextElement;
    public chambersTalkButtons!: Elements.LinkedItemsElement<ContentItem>;
    public faq!: Elements.LinkedItemsElement<ContentItem>;
    public brandcolorcode!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'attributes_heading_1') {
                    return 'attributesHeading1';
                }
                if (elementName === 'attributes_items_1') {
                    return 'attributesItems1';
                }
                if (elementName === 'fdi_investment_destination_heading') {
                    return 'fdiInvestmentDestinationHeading';
                }
                if (elementName === 'fdi_investment_destination_cta') {
                    return 'fdiInvestmentDestinationCta';
                }
                if (elementName === 'fdi_investment_destination_items') {
                    return 'fdiInvestmentDestinationItems';
                }
                if (elementName === 'attributes_heading_2') {
                    return 'attributesHeading2';
                }
                if (elementName === 'attributes_items_2') {
                    return 'attributesItems2';
                }
                if (elementName === 'benefits_buttons') {
                    return 'benefitsButtons';
                }
                if (elementName === 'chambers_talk_heading') {
                    return 'chambersTalkHeading';
                }
                if (elementName === 'chambers_talk_image') {
                    return 'chambersTalkImage';
                }
                if (elementName === 'chambers_talk_content') {
                    return 'chambersTalkContent';
                }
                if (elementName === 'chambers_talk_buttons') {
                    return 'chambersTalkButtons';
                }
                return elementName;
            })
        });
    }
}
