
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Tue Aug 01 2023 11:40:49 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Postshowreportyear extends ContentItem {
    public year!: Elements.TextElement;
    public items!: Elements.LinkedItemsElement<ContentItem>;
}
