
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Sep 04 2024 11:19:55 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Pressrelaseitem extends ContentItem {
    public name!: Elements.TextElement;
    public image!: Elements.AssetsElement;
    public heading!: Elements.TextElement;
    public subheading!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public websiteLink!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'website_link') {
                    return 'websiteLink';
                }
                return elementName;
            })
        });
    }
}
