
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Sep 04 2024 11:19:55 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Pressrelease extends ContentItem {
    public pagetitle!: Elements.TextElement;
    public bannerheading!: Elements.TextElement;
    public pressreleaseitem!: Elements.LinkedItemsElement<ContentItem>;
    public metatitle!: Elements.TextElement;
    public metadescription!: Elements.TextElement;
}
