
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Tue Dec 17 2024 18:07:37 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Regionalpitchpagestartup extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.TextElement;
    public ctabutton!: Elements.LinkedItemsElement<ContentItem>;
    public date!: Elements.TextElement;
    public bannerimage!: Elements.AssetsElement;
    public aboutheading!: Elements.TextElement;
    public aboutcontent!: Elements.TextElement;
    public sectorheading!: Elements.TextElement;
    public sectoritems!: Elements.LinkedItemsElement<ContentItem>;
    public eligiblitycriteriaheading!: Elements.TextElement;
    public eligitbilitycriteriaitems!: Elements.LinkedItemsElement<ContentItem>;
    public processheading!: Elements.TextElement;
    public processitems!: Elements.LinkedItemsElement<ContentItem>;
    public prizeheading!: Elements.TextElement;
    public prizeitems!: Elements.LinkedItemsElement<ContentItem>;
    public registerheading!: Elements.TextElement;
    public registersubheading!: Elements.TextElement;
    public regions!: Elements.LinkedItemsElement<ContentItem>;
    public seometadata!: Elements.LinkedItemsElement<ContentItem>;
}
