
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Oct 10 2022 16:01:57 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Reportitem extends ContentItem {
    public name!: Elements.TextElement;
    public reportpdf!: Elements.AssetsElement;
    public image!: Elements.AssetsElement;
}
