
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Nov 22 2024 12:25:52 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Seometadata extends ContentItem {
    public pagetitle!: Elements.TextElement;
    public metatitle!: Elements.TextElement;
    public metadescription!: Elements.TextElement;
    public metakeywords!: Elements.TextElement;
    public ogtype!: Elements.TextElement;
    public ogimage!: Elements.AssetsElement;
    public twitterCard!: Elements.TextElement;
    public twitterImage!: Elements.AssetsElement;
    public author!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'twitter_card') {
                    return 'twitterCard';
                }
                if (elementName === 'twitter_image') {
                    return 'twitterImage';
                }
                return elementName;
            })
        });
    }
}
