
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Tue Oct 22 2024 17:10:15 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Sessionspeaker extends ContentItem {
    public name!: Elements.TextElement;
    public partnershipwith!: Elements.TextElement;
    public portfolio!: Elements.MultipleChoiceElement;
    public content!: Elements.RichTextElement;
    public location!: Elements.TextElement;
    public time!: Elements.TextElement;
    public startTime!: Elements.DateTimeElement;
    public endTime!: Elements.DateTimeElement;
    public room!: Elements.TextElement;
    public speakers!: Elements.LinkedItemsElement<ContentItem>;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'start_time') {
                    return 'startTime';
                }
                if (elementName === 'end_time') {
                    return 'endTime';
                }
                return elementName;
            })
        });
    }
}
