
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Jul 10 2025 14:10:27 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Sideforumitem2026 extends ContentItem {
    public sessionname!: Elements.TextElement;
    public images!: Elements.AssetsElement;
    public entities!: Elements.TextElement;
    public sessioncontent!: Elements.RichTextElement;
    public entityitems!: Elements.LinkedItemsElement<ContentItem>;
    public relateditems!: Elements.LinkedItemsElement<ContentItem>;
}
