
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Jul 10 2025 14:28:30 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Sideforumentityitem extends ContentItem {
    public name!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public logo!: Elements.AssetsElement;
    public image!: Elements.AssetsElement;
    public websitelink!: Elements.TextElement;
}
