
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Oct 18 2024 17:23:18 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Speakers2024 extends ContentItem {
    public heading!: Elements.TextElement;
    public items!: Elements.LinkedItemsElement<ContentItem>;
    public displaycount!: Elements.NumberElement;
}
