
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Tue Dec 10 2024 09:01:17 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Speakers2025 extends ContentItem {
    public heading!: Elements.TextElement;
    public items!: Elements.LinkedItemsElement<ContentItem>;
}
