
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Dec 19 2024 09:50:14 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Sponsorspageitem extends ContentItem {
    public pagetitle!: Elements.TextElement;
    public name!: Elements.TextElement;
    public logo!: Elements.AssetsElement;
    public content!: Elements.RichTextElement;
    public website!: Elements.TextElement;
    public sponsorType!: Elements.TextElement;
    public metatitle!: Elements.TextElement;
    public metadescription!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'sponsor_type') {
                    return 'sponsorType';
                }
                return elementName;
            })
        });
    }
}
