
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Thu Nov 02 2023 10:04:01 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Startuppartnersbanneritem extends ContentItem {
    public heading!: Elements.TextElement;
    public image!: Elements.AssetsElement;
    public content!: Elements.RichTextElement;
}
