
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Sep 13 2024 12:10:16 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Startupunicornpage extends ContentItem {
    public pagetitle!: Elements.TextElement;
    public metatitle!: Elements.TextElement;
    public metadescription!: Elements.TextElement;
    public herosectionheading!: Elements.TextElement;
    public herosectionsubheading!: Elements.TextElement;
    public herosectioncta!: Elements.LinkedItemsElement<ContentItem>;
    public aboutheading!: Elements.TextElement;
    public aboutcontent!: Elements.RichTextElement;
    public aboutimage!: Elements.AssetsElement;
    public keybenefits!: Elements.LinkedItemsElement<ContentItem>;
    public keybenefitimage!: Elements.AssetsElement;
    public forecastinfoheading!: Elements.TextElement;
    public forecastinfocontent!: Elements.RichTextElement;
    public forecastimage!: Elements.AssetsElement;
    public ctacard!: Elements.AssetsElement;
}
