
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Dec 16 2024 14:25:40 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Tradetechforumwhattoexpect extends ContentItem {
    public heading!: Elements.TextElement;
    public items!: Elements.LinkedItemsElement<ContentItem>;
}
