
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Dec 16 2024 14:41:41 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Tradetechforumhome extends ContentItem {
    public heroheading!: Elements.TextElement;
    public herosubheading!: Elements.TextElement;
    public eventdatevenue!: Elements.TextElement;
    public ctabutton!: Elements.LinkedItemsElement<ContentItem>;
    public herobackgroundvideolink!: Elements.TextElement;
    public herobackgroundimage!: Elements.AssetsElement;
    public aboutheading!: Elements.TextElement;
    public aboutcontent!: Elements.RichTextElement;
    public aboutimage!: Elements.AssetsElement;
    public aboutmoreinfo!: Elements.RichTextElement;
    public statsitems!: Elements.LinkedItemsElement<ContentItem>;
    public keymessageheading!: Elements.TextElement;
    public keymessageitems!: Elements.LinkedItemsElement<ContentItem>;
    public whattoexpectheading!: Elements.TextElement;
    public whattoexpectitems!: Elements.LinkedItemsElement<ContentItem>;
    public keyinsightsheading!: Elements.TextElement;
    public keyinsightsitems!: Elements.LinkedItemsElement<ContentItem>;
    public aimaccessheading!: Elements.TextElement;
    public aimaccesscontent!: Elements.RichTextElement;
}
