
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Fri Nov 01 2024 12:58:42 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TravelPartnerPage extends ContentItem {
    public pagetitle!: Elements.TextElement;
    public metatitle!: Elements.TextElement;
    public metadescription!: Elements.TextElement;
    public bannerimage!: Elements.AssetsElement;
    public heading!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public logo!: Elements.AssetsElement;
    public serviceheading!: Elements.TextElement;
    public serviceitems!: Elements.LinkedItemsElement<ContentItem>;
    public ctabutton!: Elements.LinkedItemsElement<ContentItem>;
}
