
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Mon Feb 03 2025 10:40:10 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Visitorregisterlandingpage extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.TextElement;
    public bannerimage!: Elements.AssetsElement;
    public visitorpassname!: Elements.TextElement;
    public ctacontent!: Elements.RichTextElement;
    public seometadata!: Elements.LinkedItemsElement<ContentItem>;
}
